services:
  financeiro:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financeiro
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    networks:
      - deploy_default

networks:
  deploy_default:
    external: true
